[build-system]
build-backend = "scikit_build_core.build"
requires = ["scikit-build-core >=0.4.3", "nanobind >=1.3.2"]

[project]
authors = [
  {name = "PyVista Developers", email = "info@pyvista.org"}
]
classifiers = [
  "Intended Audience :: Science/Research",
]
dependencies = [
  "numpy"
  "pyvista"
]
description = "Rapidly read in PLY files using a wrapper over miniply"
name = "pyminiply"
readme = "README.rst"
requires-python = ">=3.8"
version = "0.3.dev0"
